name: Publish package to NPM
on:
  push:
    branches:
      - "main"
    tags:
      - v.**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      # vue-plyr-queue
      - name: vue-plyr-queue | Check package version
        id: vue-plyr-queue
        uses: PostHog/check-package-version@v2
        with:
          path: ./packages/vue-plyr-queue

      # Install dependencies
      - name: Install dependencies
        if: steps.vue-plyr-queue.outputs.is-new-version == 'true' || steps.vue-plyr.outputs.is-new-version == 'true'
        run: pnpm install

      # Build
      - name: vue-plyr-queue | Build
        if: steps.vue-plyr-queue.outputs.is-new-version == 'true'
        run: pnpm --filter=@mellkam/vue-plyr-queue build

      # Publish
      - name: vue-plyr-queue | Publish
        if: steps.vue-plyr-queue.outputs.is-new-version == 'true'
        run: pnpm --filter=@mellkam/vue-plyr-queue publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
